#!/bin/bash
#SBATCH --job-name=pa_pb1_wide
#SBATCH --partition=default1_gpu
#SBATCH --output=pa_pb1_wide_%A_%a.out
#SBATCH --error=pa_pb1_wide_%A_%a.err
#SBATCH --no-requeue
#SBATCH --gres=gpu:1
#SBATCH --exclude=aar183,aar184,aar185,aar031,aar032,aar019
#SBATCH --cpus-per-task=8
#SBATCH --mem=24G
#SBATCH --time=0-06:00:00
#SBATCH --array=0-5

# =============================================================================
# Wide search — 6 selected protocols (see protocol_selection_wider_run.md)
#
#  Group A – generate from scratch (generate_sequences.py, n=100 each)
#    0  gen_energy_A        : ew low   (1a=0.02 1b=0.05 2=0.02 3=0.05)  → best mean
#    1  gen_energy_C        : ew high  (1a=0.05 1b=0.20 2=0.05 3=0.50)  → best outliers
#
#  Group B – optimize from wide_input_sequences.txt (optimize_sequences.py)
#             Input: ~20-30 sequences generated by the energy model
#    2  opt_hard_energy_C   : stage 3 only,          ew3=0.50,  n=1/seq  → fast screen
#    3  opt_anneal_noenergy : stage 2+3,              no energy, n=4/seq  → structural refinement
#    4  opt_anneal_energy_B : stage 2+3, ew2=0.02,   ew3=0.20,  n=4/seq  → medium energy
#    5  opt_anneal_energy_C : stage 2+3, ew2=0.05,   ew3=0.50,  n=4/seq  → high energy
# =============================================================================

PROTO_NAMES=(
    "gen_energy_A"
    "gen_energy_C"
    "opt_hard_energy_C"
    "opt_anneal_noenergy"
    "opt_anneal_energy_B"
    "opt_anneal_energy_C"
)

PROTO=${PROTO_NAMES[$SLURM_ARRAY_TASK_ID]}

# ── Paths ─────────────────────────────────────────────────────────────────────
SHARED=/home/share_nfs/342-Projets_BGE/342.3-Gen-Chem/342.3.2-BioInfo/342.3.2.8-SeqModels
CODEBASE=${SHARED}/protein_design/colabdesign_energy_guidance
SCRIPT_DIR=${CODEBASE}/prg/PA_PB1

GEN_SCRIPT=${SCRIPT_DIR}/generate_sequences.py
OPT_SCRIPT=${SCRIPT_DIR}/optimize_sequences.py
SEQ_FILE=${SCRIPT_DIR}/input_sequences.txt   # energy-model-generated sequences
OUTDIR=${SCRIPT_DIR}/results/run2_wide
mkdir -p ${OUTDIR}

# ── Environment ───────────────────────────────────────────────────────────────
source ${SHARED}/miniforge3/bin/activate colabdesign
source ${CODEBASE}/.env

CUDNN_LIB=${SHARED}/miniforge3/envs/colabdesign/lib/python3.10/site-packages/nvidia/cudnn/lib
export LD_LIBRARY_PATH=$CUDNN_LIB:$LD_LIBRARY_PATH
export PYTHONPATH=${CODEBASE}:$PYTHONPATH

# ── Diagnostics ───────────────────────────────────────────────────────────────
echo "Job ID       : $SLURM_JOB_ID"
echo "Array task   : $SLURM_ARRAY_TASK_ID  →  protocol: $PROTO"
echo "Node         : $SLURMD_NODENAME"
echo "Start time   : $(date)"
echo "---------------------------------------------"
nvidia-smi | head -15
echo "---------------------------------------------"

# ── GPU check ─────────────────────────────────────────────────────────────────
python3 - << 'PYEOF'
import jax
devices = jax.devices()
print(f"JAX devices: {devices}")
if not any(d.platform == "gpu" for d in devices):
    raise SystemExit("WARNING: No GPU found — aborting.")
print(f"GPU check passed: {devices[0]}")
PYEOF

if [ $? -ne 0 ]; then
    echo "ERROR: GPU check failed. Exiting."
    exit 1
fi

# ── Run protocol ──────────────────────────────────────────────────────────────
cd ${SCRIPT_DIR}
OUTPUT=${OUTDIR}/${PROTO}.json
echo "Output file  : $OUTPUT"
echo "Running protocol: $PROTO ..."

case "$PROTO" in

    # ── Group A: generate from scratch ─────────────────────────────────────
    gen_energy_A)
        python3 $GEN_SCRIPT -n 100 \
            --ew_1a 0.02 --ew_1b 0.05 --ew_2 0.02 --ew_3 0.05 \
            -o $OUTPUT
        ;;

    gen_energy_C)
        python3 $GEN_SCRIPT -n 100 \
            --ew_1a 0.05 --ew_1b 0.20 --ew_2 0.05 --ew_3 0.50 \
            -o $OUTPUT
        ;;

    # ── Group B: optimize from energy-model sequences ───────────────────────
    # Fast hard screen: stage 3 only, 1 seed/seq × ~20-30 seqs
    opt_hard_energy_C)
        python3 $OPT_SCRIPT --seq_file $SEQ_FILE \
            --iters_2 0 --ew_3 0.50 -n 1 \
            -o $OUTPUT
        ;;

    # Structural refinement without energy bias: 4 seeds/seq × ~20-30 seqs
    opt_anneal_noenergy)
        python3 $OPT_SCRIPT --seq_file $SEQ_FILE \
            --ew_2 0.00 --ew_3 0.00 -n 4 \
            -o $OUTPUT
        ;;

    opt_anneal_energy_B)
        python3 $OPT_SCRIPT --seq_file $SEQ_FILE \
            --ew_2 0.02 --ew_3 0.20 -n 4 \
            -o $OUTPUT
        ;;

    opt_anneal_energy_C)
        python3 $OPT_SCRIPT --seq_file $SEQ_FILE \
            --ew_2 0.05 --ew_3 0.50 -n 4 \
            -o $OUTPUT
        ;;

    *)
        echo "ERROR: unknown protocol '$PROTO'"
        exit 1
        ;;
esac

echo "---------------------------------------------"
echo "End time : $(date)"
